"""create_user_tables_initial

Revision ID: 33e5bd914d43
Revises: 
Create Date: 2026-07-24 02:34:04.872820+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33e5bd914d43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('auth_user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth_user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_user_profiles_auth_user_id', 'user_profiles', ['auth_user_id'], unique=False)
    op.create_index('ix_user_profiles_created_at', 'user_profiles', ['created_at'], unique=False)
    op.create_index('ix_user_profiles_is_deleted', 'user_profiles', ['is_deleted'], unique=False)
    op.create_index('ix_user_profiles_username', 'user_profiles', ['username'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_name', sa.String(length=100), nullable=False),
    sa.Column('badge_icon', sa.String(length=200), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_name', name='uq_badges_user_badge')
    )
    op.create_index('ix_badges_user_id', 'badges', ['user_id'], unique=False)
    op.create_table('followers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_id', sa.UUID(), nullable=False),
    sa.Column('following_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('follower_id != following_id', name='ck_followers_no_self_follow'),
    sa.ForeignKeyConstraint(['follower_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_followers_follower_following')
    )
    op.create_index('ix_followers_follower_id', 'followers', ['follower_id'], unique=False)
    op.create_index('ix_followers_following_id', 'followers', ['following_id'], unique=False)
    op.create_table('interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interest', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'interest', name='uq_interests_user_interest')
    )
    op.create_index('ix_interests_user_id', 'interests', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('travel_style', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('adventure_level', sa.String(length=50), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('preferred_destinations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('profile_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_preferences_user_id', 'preferences', ['user_id'], unique=False)
    op.create_table('reputation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('explorer_score', sa.Integer(), nullable=False),
    sa.Column('community_score', sa.Integer(), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=False),
    sa.Column('expeditions_joined', sa.Integer(), nullable=False),
    sa.Column('expeditions_organized', sa.Integer(), nullable=False),
    sa.Column('guide_interactions', sa.Integer(), nullable=False),
    sa.Column('reviews_received', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_reputation_explorer_score', 'reputation', ['explorer_score'], unique=False)
    op.create_index('ix_reputation_user_id', 'reputation', ['user_id'], unique=False)
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('STORY', 'COMMUNITY', 'EXPEDITION', 'GUIDE')", name='ck_saved_items_entity_type'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_saved_items_user_entity')
    )
    op.create_index('ix_saved_items_entity_type', 'saved_items', ['entity_type'], unique=False)
    op.create_index('ix_saved_items_user_entity_type', 'saved_items', ['user_id', 'entity_type'], unique=False)
    op.create_index('ix_saved_items_user_id', 'saved_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_saved_items_user_id', table_name='saved_items')
    op.drop_index('ix_saved_items_user_entity_type', table_name='saved_items')
    op.drop_index('ix_saved_items_entity_type', table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index('ix_reputation_user_id', table_name='reputation')
    op.drop_index('ix_reputation_explorer_score', table_name='reputation')
    op.drop_table('reputation')
    op.drop_index('ix_preferences_user_id', table_name='preferences')
    op.drop_table('preferences')
    op.drop_index('ix_interests_user_id', table_name='interests')
    op.drop_table('interests')
    op.drop_index('ix_followers_following_id', table_name='followers')
    op.drop_index('ix_followers_follower_id', table_name='followers')
    op.drop_table('followers')
    op.drop_index('ix_badges_user_id', table_name='badges')
    op.drop_table('badges')
    op.drop_index('ix_user_profiles_username', table_name='user_profiles')
    op.drop_index('ix_user_profiles_is_deleted', table_name='user_profiles')
    op.drop_index('ix_user_profiles_created_at', table_name='user_profiles')
    op.drop_index('ix_user_profiles_auth_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
